-- create the user
CREATE USER PSM
  IDENTIFIED BY psm
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;

-- grant/revoke role privileges
GRANT RESOURCE TO PSM;

GRANT CONNECT TO PSM;

GRANT DBA TO PSM;

-- grant/revoke system privileges
GRANT CREATE SESSION TO PSM;

GRANT UNLIMITED TABLESPACE TO PSM;